# -*- coding: utf-8 -*-
"""fix_app1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yq5Z4YTOhuTZL3pKgD3Q8WaLonuV_kDH
"""

from flask import Flask, request, render_template
import os
import requests
import IPython
from typhoon_ocr import ocr_document
from PIL import Image

app = Flask(__name__)
UPLOAD_FOLDER = 'static'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# API keys
os.environ['TYPHOON_OCR_API_KEY'] = 'sk-SMrtW1JrLSLfYMHZhhD8Kk13A6ZuxnEuZN9RoenbaHbytiF6'
VAJA_API_KEY = 'bBPTrefkfhEYXr89NuWmaKX585b32al6'

@app.route('/', methods=['GET', 'POST'])
def index():
    text = ''
    audio_file = None
    error_message = None

    if request.method == 'POST':
        try:
            file = request.files['image']
            image_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
            file.save(image_path)

            # ตรวจสอบว่าไฟล์ภาพเปิดได้หรือไม่
            try:
                Image.open(image_path).verify()
            except Exception as e:
                error_message = f"[❌ ERROR: ภาพไม่สมบูรณ์หรือเปิดไม่ได้] {str(e)}"
                return render_template('index.html', markdown=error_message)

            # OCR
            text = ocr_document(image_path, task_type="default")

            # เซฟไฟล์ผล OCR
            with open(os.path.join(app.config['UPLOAD_FOLDER'], 'ocr_output.txt'), 'w', encoding='utf-8') as f:
                f.write(text)

            # สังเคราะห์เสียง
            url = 'https://api.aiforthai.in.th/vaja9/synth_audiovisual'
            headers = {'Apikey': VAJA_API_KEY, 'Content-Type': 'application/json'}
            data = {'input_text': text, 'speaker': 1, 'phrase_break': 0, 'audiovisual': 0}
            response = requests.post(url, json=data, headers=headers)

            if response.status_code == 200:
                wav_url = response.json().get('wav_url')
                resp = requests.get(wav_url, headers={'Apikey': VAJA_API_KEY})
                if resp.status_code == 200:
                    output_path = os.path.join(app.config['UPLOAD_FOLDER'], 'result.wav')
                    with open(output_path, 'wb') as f:
                        f.write(resp.content)
                    audio_file = 'result.wav'
                else:
                    text += "\n\n[❌ ERROR ดาวน์โหลดเสียงล้มเหลว]"
            else:
                text += "\n\n[❌ ERROR แปลงเสียงล้มเหลว]"

        except Exception as e:
            error_message = f"[❌ ERROR: {str(e)}]"

    return render_template('index.html', markdown=text or error_message, image_file=file.filename if 'file' in locals() else None, audio_file=audio_file)

if __name__ == '__main__':
    app.run(debug=True)
